# Autor: Daniel Benjamin Perez Morales
# GitHub: https://github.com/DanielBenjaminPerezMoralesDev13
# Gitlab: https://gitlab.com/DanielBenjaminPerezMoralesDev13
# Correo electrónico: danielperezdev@proton.me

secrets:
  MONGO_DB_USERNAME:
    file: ./secrets/MONGO_DB_USERNAME.txt
  MONGO_DB_PWD:
    file: ./secrets/MONGO_DB_PWD.txt
  MONGO_INITDB_ROOT_USERNAME:
    file: ./secrets/MONGO_INITDB_ROOT_USERNAME.txt
  MONGO_INITDB_ROOT_PASSWORD:
    file: ./secrets/MONGO_INITDB_ROOT_PASSWORD.txt

services:
  app:
    healthcheck:
      test: ["CMD", "wget", "-SqO-", "localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    container_name: container-app
    image: d4nitrix13/my-app-private:latest
    ports:
      - 3000:3000
    env_file:
      - app.env
  mongo-demo:
    container_name: container-mongo-demo
    image: mongo:latest
    ports:
      - 27017:27017
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_INITDB_ROOT_PASSWORD
  mongo-express:
    container_name: container-mongo-express
    depends_on:
      - mongo-demo
    image: mongo-express
    ports:
      - 8081:8081
    entrypoint:
      - /bin/sh
      - -c
      - |
        until nc -zv mongo-demo 27017; do
          echo "Waiting For Mongo";
          sleep 1;
        done;
        exec /sbin/tini -- /docker-entrypoint.sh
    env_file:
      - mongo-express.env
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_OPTIONS_EDITORTHEME: material-darker
      ME_CONFIG_REQUEST_SIZE: 100kb
      ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_SITE_COOKIESECRET: cookiesecret
      ME_CONFIG_SITE_SESSIONSECRET: sessionsecret
      ME_CONFIG_SITE_SSL_ENABLED: false
      ME_CONFIG_MONGODB_PORT: "27017"
